// World mode data contract. world.json is generated by scripts/generate-world.js
// from resume.json + world.yaml. All leaf modules import from here — never redefine.

export type RoomId = 'journey' | 'warehouse' | 'registry' | 'contact';

export interface WorldMeta {
  name: string;
  tagline: string;
  generatedAt: string;
}

export interface JourneyBeat {
  id: string;
  date: string; // display form, e.g. "2018" or "Mar 2023"
  title: string;
  body: string; // 1-2 sentences, ink-note voice
  kind: 'education' | 'community' | 'work' | 'publication' | 'award' | 'now';
  link?: string;
}

export interface Award {
  id: string;
  title: string;
  issuer: string;
  date: string;
  caption: string;
}

export interface Exhibit {
  id: string;
  client: string;
  title: string;
  metric: string; // headline number, e.g. "27.5h → <5s"
  body: string; // card description
  tags: string[];
  date: string;
}

export interface Parcel {
  id: string; // pypi package name or repo slug
  name: string;
  pypiPackage?: string; // key into pypi-stats.json packages map
  fallbackDownloads?: string; // shown if live stats unavailable, e.g. "11.1k+"
  body: string;
  links: { label: string; url: string }[];
}

export interface ContactLink {
  id: string;
  label: string;
  url: string; // mailto:, https://
}

export interface ContactForm {
  endpoint: string; // Web3Forms-style POST endpoint; empty string = mailto fallback
  accessKey: string;
  mailto: string;
}

export interface EasterEgg {
  id: 'serverRack' | 'speedometer' | 'quantumCat' | 'rubberDuck';
  lines: string[]; // speech-bubble lines; rack/speedometer use lines[0] as caption
  link?: string;
}

export interface RoomCopy {
  id: RoomId;
  label: string; // door sign, e.g. "JOURNEY"
  hint: string; // quest banner hint shown on entry
}

export interface WorldData {
  meta: WorldMeta;
  rooms: RoomCopy[];
  journey: { beats: JourneyBeat[]; awards: Award[]; skills?: string[] };
  warehouse: { exhibits: Exhibit[] };
  registry: { headline: string; parcels: Parcel[] };
  contact: { links: ContactLink[]; form: ContactForm };
  easterEggs: EasterEgg[];
}

// ---- Engine state ----

export type WorldStage =
  | 'loading' // preloader visible, textures generating
  | 'cover' // title page gate; click = audio unlock + enter
  | 'corridor'
  | 'room';

export type TeleportPhase = null | 'closing' | 'teleporting' | 'opening';

export interface WorldState {
  stage: WorldStage;
  currentRoom: RoomId | null;
  teleport: { phase: TeleportPhase; target: RoomId | null };
  visited: RoomId[];
}

export type AchievementId =
  | 'open_notebook'
  | 'walk_corridor'
  | 'fly_journey'
  | 'inspect_exhibit'
  | 'open_parcel'
  | 'reach_out';

export interface AchievementDef {
  id: AchievementId;
  title: string;
  label: string; // the tutorial hint, e.g. "Scroll to walk the corridor"
}

export type SoundName =
  | 'pencil' // loop, preloader
  | 'tear' // page tear
  | 'pageFlip' // door/card open
  | 'doorCreak' // hover ajar
  | 'thud' // close/land
  | 'pop' // parcel/balloon pop
  | 'chime' // achievement (two-tone)
  | 'ambience'; // soft room tone loop
