// ContactForm: a DOM modal styled like a hand-torn paper note — real <form>
// with ink-underline inputs, Patrick Hand body / Caveat labels, live char
// counters, and a hand-dashed SEND button. Mounted by Contact.tsx through an
// independent ReactDOM root (see useDomOverlay there), which re-provides the
// current WorldDataCtx value so this component can read data.contact.form
// the same way every other world module reads its data — via useWorldData()
// — despite living outside the r3f-rendered tree.
//
// Submission: chooseSubmitMode() decides between POSTing JSON to the
// configured endpoint or falling back to a mailto: link, exactly mirroring
// contactValidation.ts's pure decision so there's a single source of truth
// for that branch.
//
// Paper re-skin (punchlist #11/#25/#29 — "generic flat SaaS card", "plain
// white... sharp straight border", "off-palette neutral gray scrim"):
//   - The panel silhouette is clipped by TORN_EDGE_CLIP_PATH, a hand-picked
//     (not runtime-randomized — see its own comment) jagged polygon applied
//     to all four edges, so the note reads as torn paper rather than a
//     rounded-rect card. Coordinates are in the polygon's own 0-100%
//     space, so the shape stays proportionally identical regardless of the
//     modal's actual rendered pixel size (which varies with validation-error
//     copy) — no measurement/redraw needed on content changes.
//   - The background is a real procedural paper-grain tile, generated once
//     from textures/notebook.ts's drawPaperBackground (the exact same grain
//     used on every in-scene paper surface) via a canvas -> data URL, tiled
//     with CSS background-repeat. Reusing the shared drawer keeps this DOM
//     modal visually consistent with the R3F-rendered paper elsewhere
//     instead of inventing a second paper texture.
//   - `filter: drop-shadow(...)` is used instead of `box-shadow` because
//     box-shadow follows the element's box, not its clip-path — it would
//     draw a rectangular shadow behind a jagged shape.
import { useEffect, useMemo, useRef, useState } from 'react';
import type { ChangeEvent, CSSProperties, FormEvent } from 'react';
import { FONTS } from '../contracts';
import { useWorldData } from '../state/hooks';
import { BLUEPRINT } from '../blueprint/palette';
import { PALETTE, drawPaperBackground } from '../textures/notebook';
import {
  FIELD_CAPS,
  buildEndpointPayload,
  buildMailto,
  chooseSubmitMode,
  truncate,
  validateForm,
  type ContactFormErrors,
  type ContactFormFields,
} from './contactValidation';

export interface ContactFormProps {
  onClose: () => void;
}

const BASE_URL = import.meta.env.BASE_URL || '/';

const PAPER = PALETTE.paper;
const INK = PALETTE.ink;
const BLUE = PALETTE.blue;
const RED = PALETTE.red;
const GREEN = PALETTE.green;

const EMPTY_FIELDS: ContactFormFields = { email: '', subject: '', message: '' };

type SubmitStatus = 'idle' | 'submitting' | 'success' | 'error';

/**
 * Hand-picked torn-edge polygon (all four sides), in the CSS clip-path
 * percentage space (0-100% of the element's own width/height). Deliberately
 * NOT generated by a runtime seeded-random routine — a jagged clip-path is
 * one wrong coordinate away from a self-intersecting/invisible polygon, and
 * this component has no browser available to visually confirm a generated
 * one renders correctly. Every point was hand-verified to move monotonically
 * along its edge (x strictly increasing along the top, y strictly increasing
 * down the right side, etc.) with a small perpendicular jitter (max ~3% of
 * the box's own width/height) so the four bands never overlap and the path
 * can't cross itself. PADDING below is sized generously (2rem+) to keep
 * every jitter clear of the actual text content.
 */
const TORN_EDGE_CLIP_PATH =
  'polygon(' +
  '0% 2%, 10% 0.5%, 20% 2.5%, 30% 0.8%, 40% 2.2%, 50% 0.6%, 60% 2.4%, 70% 1%, 80% 2.2%, 90% 0.5%, 100% 2%, ' +
  '98% 12%, 100% 22%, 97.5% 32%, 100% 42%, 98% 52%, 100% 62%, 97.5% 72%, 100% 82%, 98% 92%, 100% 98%, ' +
  '90% 100%, 80% 97.5%, 70% 99.5%, 60% 97.8%, 50% 99.8%, 40% 97.6%, 30% 99.6%, 20% 97.8%, 10% 99.5%, 0% 98%, ' +
  '2% 88%, 0% 78%, 2.5% 68%, 0% 58%, 2% 48%, 0% 38%, 2.5% 28%, 0% 18%, 2% 8%' +
  ')';

const FONT_FACE_CSS = `
  @font-face {
    font-family: 'World Patrick Hand';
    src: url('${BASE_URL}${FONTS.hand}') format('truetype');
    font-weight: 400;
    font-display: swap;
  }
  @font-face {
    font-family: 'World Caveat';
    src: url('${BASE_URL}${FONTS.caveat}') format('truetype');
    font-weight: 400 700;
    font-display: swap;
  }
  .world-contact-field:focus {
    border-bottom-color: ${BLUE} !important;
  }
  .world-contact-send {
    /* Base state lives in CSS (not the inline style prop) so the :hover rule
       below — same property, more specific selector — actually wins. An
       inline style on the element always beats a class selector regardless
       of pseudo-classes, which is why the previous hover fill never painted:
       background/border-color/color were all set inline too. */
    background: transparent;
    border-color: ${INK};
    color: ${INK};
    transition: background 0.15s ease, color 0.15s ease, border-color 0.15s ease, transform 0.15s ease;
  }
  .world-contact-send:hover:not(:disabled) {
    transform: scale(1.03) rotate(-0.3deg);
    background: ${BLUEPRINT.accent};
    border-color: ${BLUEPRINT.accent};
    color: ${PAPER};
  }
  .world-contact-send:disabled {
    opacity: 0.6;
    cursor: default;
  }
`;

/** Builds the paper-grain tile once (data URL, cheap to memoize) using the
 * same drawPaperBackground() every in-scene paper surface uses. Returns ''
 * if no 2D canvas context is available (e.g. an unusual embedding) — the
 * flat PAPER backgroundColor fallback still applies in that case. */
function buildPaperTileUrl(seed: number, size = 220): string {
  if (typeof document === 'undefined') return '';
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d');
  if (!ctx) return '';
  drawPaperBackground(ctx, size, size, seed);
  return canvas.toDataURL('image/png');
}

export function ContactForm({ onClose }: ContactFormProps): JSX.Element {
  const data = useWorldData();
  const config = data.contact.form;

  const [fields, setFields] = useState<ContactFormFields>(EMPTY_FIELDS);
  const [errors, setErrors] = useState<ContactFormErrors>({});
  const [status, setStatus] = useState<SubmitStatus>('idle');
  const [statusMessage, setStatusMessage] = useState('');

  const paperTileUrl = useMemo(() => buildPaperTileUrl(11), []);

  const firstInputRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    firstInputRef.current?.focus();
  }, []);

  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent): void => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [onClose]);

  const handleChange =
    (field: keyof ContactFormFields) =>
    (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>): void => {
      const next = truncate(e.target.value, FIELD_CAPS[field]);
      setFields((prev) => ({ ...prev, [field]: next }));
    };

  const handleSubmit = async (e: FormEvent<HTMLFormElement>): Promise<void> => {
    e.preventDefault();
    const result = validateForm(fields);
    setErrors(result.errors);
    if (!result.ok) return;

    const mode = chooseSubmitMode(config);

    if (mode === 'mailto') {
      window.location.href = buildMailto(config.mailto, fields);
      setStatus('success');
      setStatusMessage('Message sent ✓');
      return;
    }

    setStatus('submitting');
    setStatusMessage('');
    try {
      const payload = buildEndpointPayload(config.accessKey, fields);
      const res = await fetch(config.endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
        body: JSON.stringify(payload),
      });

      let success = res.ok;
      try {
        const json: unknown = await res.json();
        if (json !== null && typeof json === 'object' && 'success' in json) {
          success = res.ok && Boolean((json as { success?: unknown }).success);
        }
      } catch {
        // non-JSON response body; fall back to the HTTP status alone
      }

      if (!success) throw new Error('Delivery failed — try again?');
      setStatus('success');
      setStatusMessage('Message sent ✓');
    } catch (err) {
      setStatus('error');
      setStatusMessage(err instanceof Error ? err.message : 'Something went wrong.');
    }
  };

  const submitting = status === 'submitting';
  const succeeded = status === 'success';

  return (
    <div
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 10000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        // Warm ink scrim (was a neutral gray, punchlist #29) so the backdrop
        // matches the paper/ink palette instead of clashing with it. Uses an
        // umber rgb (R>G>B) rather than PALETTE.ink's #2a2a2a, which is
        // itself a true neutral gray (R=G=B) and still read as flat gray
        // once composited over the scene.
        background: 'rgba(48, 38, 30, 0.55)',
        padding: '1.5rem',
      }}
    >
      <style>{FONT_FACE_CSS}</style>

      <div
        onMouseDown={(e) => e.stopPropagation()}
        style={{
          position: 'relative',
          width: '100%',
          maxWidth: 440,
          backgroundColor: PAPER,
          backgroundImage: paperTileUrl ? `url(${paperTileUrl})` : undefined,
          backgroundRepeat: 'repeat',
          backgroundSize: '220px 220px',
          color: INK,
          border: `2px solid ${INK}`,
          clipPath: TORN_EDGE_CLIP_PATH,
          WebkitClipPath: TORN_EDGE_CLIP_PATH,
          transform: 'rotate(-0.5deg)',
          filter: 'drop-shadow(3px 6px 0 rgba(42,42,42,0.2)) drop-shadow(0 3px 14px rgba(42,42,42,0.18))',
          padding: '2.3rem 2rem 2rem',
          fontFamily: "'World Patrick Hand', cursive",
        }}
      >
        <button
          type="button"
          onClick={onClose}
          aria-label="Close"
          style={{
            position: 'absolute',
            top: 22,
            right: 20,
            background: 'transparent',
            border: 'none',
            color: INK,
            fontSize: '1.4rem',
            lineHeight: 1,
            cursor: 'pointer',
            fontFamily: "'World Patrick Hand', cursive",
          }}
        >
          &times;
        </button>

        <h2 style={{ margin: '0 0 0.2rem', fontSize: '2.1rem', fontFamily: "'World Caveat', cursive" }}>
          Leave a note
        </h2>
        <p style={{ margin: '0 0 1.25rem', opacity: 0.75, fontSize: '1rem' }}>
          I read every one of these.
        </p>

        <form onSubmit={handleSubmit} noValidate>
          <div style={{ marginBottom: '1rem' }}>
            <label htmlFor="world-contact-email" style={labelStyle}>
              Your email
            </label>
            <input
              ref={firstInputRef}
              id="world-contact-email"
              className="world-contact-field"
              type="email"
              value={fields.email}
              maxLength={FIELD_CAPS.email}
              onChange={handleChange('email')}
              disabled={submitting}
              style={inputStyle}
              placeholder="you@example.com"
            />
            <FieldFooter count={fields.email.length} cap={FIELD_CAPS.email} error={errors.email} />
          </div>

          <div style={{ marginBottom: '1rem' }}>
            <label htmlFor="world-contact-subject" style={labelStyle}>
              Subject
            </label>
            <input
              id="world-contact-subject"
              className="world-contact-field"
              type="text"
              value={fields.subject}
              maxLength={FIELD_CAPS.subject}
              onChange={handleChange('subject')}
              disabled={submitting}
              style={inputStyle}
              placeholder="Say hi, or pitch me a role"
            />
            <FieldFooter count={fields.subject.length} cap={FIELD_CAPS.subject} error={errors.subject} />
          </div>

          <div style={{ marginBottom: '1.25rem' }}>
            <label htmlFor="world-contact-message" style={labelStyle}>
              Message
            </label>
            <textarea
              id="world-contact-message"
              className="world-contact-field"
              value={fields.message}
              maxLength={FIELD_CAPS.message}
              onChange={handleChange('message')}
              disabled={submitting}
              rows={4}
              style={{ ...inputStyle, resize: 'vertical', minHeight: 90 }}
            />
            <FieldFooter count={fields.message.length} cap={FIELD_CAPS.message} error={errors.message} />
          </div>

          <button
            type="submit"
            className="world-contact-send"
            disabled={submitting}
            style={{
              display: 'block',
              width: '100%',
              padding: '0.65rem',
              // background/border-color/color intentionally omitted here —
              // they live in the .world-contact-send CSS rule above so the
              // :hover rule can override them (see comment there).
              borderWidth: 2,
              borderStyle: 'dashed',
              borderRadius: 8,
              fontFamily: "'World Patrick Hand', cursive",
              fontSize: '1.15rem',
              cursor: submitting ? 'default' : 'pointer',
              appearance: 'none',
              WebkitAppearance: 'none',
            }}
          >
            {submitting ? 'Sending…' : 'SEND'}
          </button>

          {status !== 'idle' && statusMessage && (
            <p
              role="status"
              style={{
                marginTop: '0.9rem',
                marginBottom: 0,
                textAlign: 'center',
                fontFamily: succeeded ? "'World Caveat', cursive" : "'World Patrick Hand', cursive",
                fontSize: succeeded ? '1.5rem' : '1.05rem',
                color: succeeded ? GREEN : status === 'error' ? RED : INK,
              }}
            >
              {statusMessage}
            </p>
          )}
        </form>
      </div>
    </div>
  );
}

const labelStyle: CSSProperties = {
  display: 'block',
  fontFamily: "'World Caveat', cursive",
  fontSize: '1.3rem',
  marginBottom: 2,
};

const inputStyle: CSSProperties = {
  width: '100%',
  boxSizing: 'border-box',
  background: 'transparent',
  border: 'none',
  borderBottom: `2px solid ${INK}`,
  padding: '0.4rem 0.2rem',
  fontFamily: "'World Patrick Hand', cursive",
  fontSize: '1.1rem',
  color: INK,
  outline: 'none',
  // Chrome/Safari otherwise paint a native inset bevel/box around <textarea>
  // (the -webkit-appearance: textarea default) regardless of the `border`
  // override above — the root cause of punchlist #25's "fully-boxed for
  // message" complaint, since email/subject (plain <input>) don't get that
  // native bevel but the message <textarea> did.
  appearance: 'none',
  WebkitAppearance: 'none',
};

interface FieldFooterProps {
  count: number;
  cap: number;
  error?: string;
}

function FieldFooter({ count, cap, error }: FieldFooterProps): JSX.Element {
  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'baseline',
        marginTop: 3,
        minHeight: '1.2em',
      }}
    >
      <span style={{ fontSize: '0.9rem', color: RED }}>{error ?? ''}</span>
      <span style={{ fontSize: '0.85rem', opacity: 0.55 }}>
        {count}/{cap}
      </span>
    </div>
  );
}
